### ISSUE TITLE
路由的地址怎么写？

### ISSUE THREAD

**Issue by qq735675958** [TingGe/egg-easy-proxy#3]
作者能否写个完整示例，按照示例配好了，测试 无任何反应？
config.easyProxy = [
    {
      host: 'https://www.tianqiapi.com/',
      match: /^\/test1/,
    },
  ];
请求 http://localhost:3000/test1/api   无任何反应 ，是我写错了吗？

**Comment by TingGe** [comment]
@qq735675958 用法只需要两个配置、比较简单，所以没单独再写example。可以直接把 test/fixtures/apps/easy-proxy-test 中的配置贴到项目中跑着试试。

你这个写法有两个问题：
1.  正则 `/^/test1/` 正确的写法是 `/^\/test1/`
2. `https://www.tianqiapi.com/test1/api` 这个URL访问后是404，所以即使代理成功也是返回404。

我看天气站有个 `https://www.tianqiapi.com/api/?version=v1` 接口，可以试试

```json
config.easyProxy = [
  {
    host: 'https://www.tianqiapi.com/',
    match: /api\/?/,
  },
];
```

这样midway或egg项目中启动debug后，访问 http://127.0.0.1:3000/api/?version=v1 和 https://www.tianqiapi.com/api/?version=v1 是一样的。

easyProxy代理后的效果
![image](https://user-images.githubusercontent.com/4074517/62420828-6cb61780-b6cb-11e9-8cca-d6e2fcd9b71b.png)

天气API站的效果
![image](https://user-images.githubusercontent.com/4074517/62420835-76d81600-b6cb-11e9-8409-4a4e379573a4.png)
